include/AVL.h
NAME
include/AVL.h
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include './stack.h'
Data Structures
struct AVLNode
struct AVLTree
Functions
struct AVLTree * init_avl ()
int insert (struct AVLTree *tree, void *data, int id)
void * remove_ID (struct AVLTree *tree, int id)
void * find (struct AVLTree *tree, int id)
void inorder (struct AVLTree *tree, struct stack *stack)
void postorder (struct AVLTree *tree, struct stack *stack)
void preorder (struct AVLTree *tree, struct stack *stack)
void stackify (struct AVLTree *tree, struct stack *stack)
void destroy_avl (struct AVLTree *tree)
Function Documentation
void destroy_avl (struct AVLTree * tree)
References destroy_avl_nodes(), AVLTree::root, and AVLTree::size.
Referenced by create_vertex(), destroy_graph_avl(), graph_init(), and main().
void* find (struct AVLTree * tree, int id)
References find_node(), and AVLTree::root.
Referenced by cleanup(), create_edge(), init(), main(), modify_edge(), remove_vertex_id(), setupEdges(), setupSelfEdge(), start_set(), test_delete(), test_find(), test_graph_add_bi_edge(), test_graph_add_edge(), test_graph_modify_bi_edge(), test_graph_modify_edge(), test_graph_modify_vertex(), test_graph_remove_bi_edge(), test_graph_remove_edge(), and test_graph_remove_vertex().
struct AVLTree* init_avl ()
References AVLTree::root, and AVLTree::size.
Referenced by create_vertex(), graph_init(), and main().
void inorder (struct AVLTree * tree, struct stack * stack)
References inorder_nodes(), AVLTree::root, and AVLTree::size.
Referenced by print_state(), test_delete(), and test_inorder().
int insert (struct AVLTree * tree, void * data, int id)
References create_node(), AVLNode::data, insert_node(), AVLTree::root, and AVLTree::size.
Referenced by create_edge(), create_vertex(), insert_node(), and test_insert().
void postorder (struct AVLTree * tree, struct stack * stack)
References postorder_nodes(), AVLTree::root, and AVLTree::size.
void preorder (struct AVLTree * tree, struct stack * stack)
References preorder_nodes(), AVLTree::root, and AVLTree::size.
Referenced by destroy_graph_avl(), fire(), print_edges(), and run_single().
void* remove_ID (struct AVLTree * tree, int id)
References AVLNode::data, remove_node(), AVLTree::root, and AVLTree::size.
Referenced by create_edge(), remove_edge(), remove_edge_id(), remove_vertex(), and test_delete().
void stackify (struct AVLTree * tree, struct stack * stack)
References AVLTree::root, AVLTree::size, and stackify_nodes().
Referenced by remove_vertex().
Author
Generated automatically by Doxygen for Topologic from the source code.