src/AVL.c
NAME
src/AVL.c
SYNOPSIS
#include '../include/AVL.h'
Functions
struct AVLTree * init_avl ()
int balance (struct AVLNode *node)
int max_height (struct AVLNode *node)
struct AVLNode * right_rotate (struct AVLNode *node)
struct AVLNode * left_rotate (struct AVLNode *node)
struct AVLNode * create_node (void *data, int id)
struct AVLNode * insert_node (struct AVLNode *node, struct AVLNode *insert)
int insert (struct AVLTree *tree, void *data, int id)
void * find_node (struct AVLNode *root, int id)
void * find (struct AVLTree *tree, int id)
struct AVLNode * minNode (struct AVLNode *node)
struct AVLNode * remove_node (struct AVLNode *root, int id, void **data)
void * remove_ID (struct AVLTree *tree, int id)
void inorder_nodes (struct AVLNode *node, struct stack *stack)
void inorder (struct AVLTree *tree, struct stack *stack)
void preorder_nodes (struct AVLNode *node, struct stack *stack)
void preorder (struct AVLTree *tree, struct stack *stack)
void postorder_nodes (struct AVLNode *node, struct stack *stack)
void postorder (struct AVLTree *tree, struct stack *stack)
void stackify_nodes (struct AVLNode *node, struct stack *stack)
void stackify (struct AVLTree *tree, struct stack *stack)
void destroy_avl_nodes (struct AVLNode *node)
void destroy_avl (struct AVLTree *tree)
Function Documentation
int balance (struct AVLNode * node)
References AVLNode::height, AVLNode::left, and AVLNode::right.
Referenced by insert_node(), and remove_node().
struct AVLNode* create_node (void * data, int id)
References AVLNode::data, AVLNode::height, AVLNode::id, AVLNode::left, and AVLNode::right.
Referenced by insert().
void destroy_avl (struct AVLTree * tree)
References destroy_avl_nodes(), AVLTree::root, and AVLTree::size.
Referenced by create_vertex(), destroy_graph_avl(), graph_init(), and main().
void destroy_avl_nodes (struct AVLNode * node)
References AVLNode::data, AVLNode::height, AVLNode::left, and AVLNode::right.
Referenced by destroy_avl().
void* find (struct AVLTree * tree, int id)
References find_node(), and AVLTree::root.
Referenced by cleanup(), create_edge(), init(), main(), modify_edge(), remove_vertex_id(), setupEdges(), setupSelfEdge(), start_set(), test_delete(), test_find(), test_graph_add_bi_edge(), test_graph_add_edge(), test_graph_modify_bi_edge(), test_graph_modify_edge(), test_graph_modify_vertex(), test_graph_remove_bi_edge(), test_graph_remove_edge(), and test_graph_remove_vertex().
void* find_node (struct AVLNode * root, int id)
References AVLNode::data, AVLNode::id, AVLNode::left, and AVLNode::right.
Referenced by find().
struct AVLTree* init_avl ()
References AVLTree::root, and AVLTree::size.
Referenced by create_vertex(), graph_init(), and main().
void inorder (struct AVLTree * tree, struct stack * stack)
References inorder_nodes(), AVLTree::root, and AVLTree::size.
Referenced by print_state(), test_delete(), and test_inorder().
void inorder_nodes (struct AVLNode * node, struct stack * stack)
References AVLNode::data, AVLNode::id, AVLNode::left, push(), and AVLNode::right.
Referenced by inorder().
int insert (struct AVLTree * tree, void * data, int id)
References create_node(), AVLNode::data, insert_node(), AVLTree::root, and AVLTree::size.
Referenced by create_edge(), create_vertex(), insert_node(), and test_insert().
struct AVLNode* insert_node (struct AVLNode * node, struct AVLNode * insert)
References balance(), AVLNode::height, AVLNode::id, insert(), AVLNode::left, left_rotate(), max_height(), AVLNode::right, and right_rotate().
Referenced by insert().
struct AVLNode* left_rotate (struct AVLNode * node)
References AVLNode::height, AVLNode::left, max_height(), and AVLNode::right.
Referenced by insert_node(), and remove_node().
int max_height (struct AVLNode * node)
References AVLNode::height, AVLNode::left, and AVLNode::right.
Referenced by insert_node(), left_rotate(), remove_node(), and right_rotate().
struct AVLNode* minNode (struct AVLNode * node)
References AVLNode::left.
Referenced by remove_node().
void postorder (struct AVLTree * tree, struct stack * stack)
References postorder_nodes(), AVLTree::root, and AVLTree::size.
void postorder_nodes (struct AVLNode * node, struct stack * stack)
References AVLNode::data, AVLNode::id, AVLNode::left, push(), and AVLNode::right.
Referenced by postorder().
void preorder (struct AVLTree * tree, struct stack * stack)
References preorder_nodes(), AVLTree::root, and AVLTree::size.
Referenced by destroy_graph_avl(), fire(), print_edges(), and run_single().
void preorder_nodes (struct AVLNode * node, struct stack * stack)
References AVLNode::data, AVLNode::id, AVLNode::left, push(), and AVLNode::right.
Referenced by preorder().
void* remove_ID (struct AVLTree * tree, int id)
References AVLNode::data, remove_node(), AVLTree::root, and AVLTree::size.
Referenced by create_edge(), remove_edge(), remove_edge_id(), remove_vertex(), and test_delete().
struct AVLNode* remove_node (struct AVLNode * root, int id, void ** data)
References balance(), AVLNode::data, AVLNode::height, AVLNode::id, AVLNode::left, left_rotate(), max_height(), minNode(), AVLNode::right, and right_rotate().
Referenced by remove_ID().
struct AVLNode* right_rotate (struct AVLNode * node)
References AVLNode::height, AVLNode::left, max_height(), and AVLNode::right.
Referenced by insert_node(), and remove_node().
void stackify (struct AVLTree * tree, struct stack * stack)
References AVLTree::root, AVLTree::size, and stackify_nodes().
Referenced by remove_vertex().
void stackify_nodes (struct AVLNode * node, struct stack * stack)
References AVLNode::data, AVLNode::height, AVLNode::left, push(), and AVLNode::right.
Referenced by stackify().
Author
Generated automatically by Doxygen for Topologic from the source code.