testing/avl_test.c
NAME
testing/avl_test.c
SYNOPSIS
#include '../include/AVL.h'
#include '../include/stack.h'
#include '../include/test.h'
Functions
void test_insert (struct AVLTree *tree, int *vals)
void test_inorder (struct AVLTree *tree)
void test_find (struct AVLTree *tree)
void test_delete (struct AVLTree *tree)
int main ()
Function Documentation
int main ()
References destroy_avl(), init_avl(), test_delete(), test_find(), test_inorder(), and test_insert().
void test_delete (struct AVLTree * tree)
References destroy_stack(), find(), init_stack(), inorder(), pop(), and remove_ID().
Referenced by main().
void test_find (struct AVLTree * tree)
References find().
Referenced by main().
void test_inorder (struct AVLTree * tree)
References destroy_stack(), init_stack(), inorder(), and pop().
Referenced by main().
void test_insert (struct AVLTree * tree, int * vals)
References insert().
Referenced by main().
Author
Generated automatically by Doxygen for Topologic from the source code.