.TH "AVLNode" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AVLNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AVL\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "struct \fBAVLNode\fP * \fBleft\fP"
.br
.ti -1c
.RI "struct \fBAVLNode\fP * \fBright\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* AVLNode::data"

.PP
Referenced by create_node(), destroy_avl_nodes(), find_node(), inorder_nodes(), insert(), postorder_nodes(), preorder_nodes(), remove_ID(), remove_node(), and stackify_nodes()\&.
.SS "int AVLNode::height"

.PP
Referenced by balance(), create_node(), destroy_avl_nodes(), insert_node(), left_rotate(), max_height(), remove_node(), right_rotate(), and stackify_nodes()\&.
.SS "int AVLNode::id"

.PP
Referenced by create_node(), find_node(), inorder_nodes(), insert_node(), postorder_nodes(), preorder_nodes(), and remove_node()\&.
.SS "struct \fBAVLNode\fP* AVLNode::left"

.PP
Referenced by balance(), create_node(), destroy_avl_nodes(), find_node(), inorder_nodes(), insert_node(), left_rotate(), max_height(), minNode(), postorder_nodes(), preorder_nodes(), remove_node(), right_rotate(), and stackify_nodes()\&.
.SS "struct \fBAVLNode\fP* AVLNode::right"

.PP
Referenced by balance(), create_node(), destroy_avl_nodes(), find_node(), inorder_nodes(), insert_node(), left_rotate(), max_height(), postorder_nodes(), preorder_nodes(), remove_node(), right_rotate(), and stackify_nodes()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
