.TH "AVLTree" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AVLTree
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AVL\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBAVLNode\fP * \fBroot\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBAVLNode\fP* AVLTree::root"

.PP
Referenced by destroy_avl(), find(), init_avl(), inorder(), insert(), postorder(), preorder(), remove_ID(), and stackify()\&.
.SS "int AVLTree::size"

.PP
Referenced by destroy_avl(), init_avl(), inorder(), insert(), postorder(), preorder(), print_graph(), print_state(), remove_ID(), and stackify()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
