.TH "destroy_edge_request" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
destroy_edge_request
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <edge\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBvertex\fP * \fBa\fP"
.br
.ti -1c
.RI "struct \fBvertex\fP * \fBb\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBvertex\fP* destroy_edge_request::a"

.PP
Referenced by procces_request()\&.
.SS "struct \fBvertex\fP* destroy_edge_request::b"

.PP
Referenced by procces_request()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
