.TH "include/edge.h" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/edge.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include '\&./vertex\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBedge\fP"
.br
.ti -1c
.RI "struct \fBedge_request\fP"
.br
.ti -1c
.RI "struct \fBdestroy_edge_request\fP"
.br
.ti -1c
.RI "struct \fBdestroy_edge_id_request\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBedge_type\fP { \fBEDGE\fP = 0, \fBBI_EDGE\fP = 1, \fBSELF_EDGE\fP = 2 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBedge_type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEDGE \fP\fP
.TP
\fB\fIBI_EDGE \fP\fP
.TP
\fB\fISELF_EDGE \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
