.TH "edge_request" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edge_request
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <edge\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBvertex\fP * \fBa\fP"
.br
.ti -1c
.RI "struct \fBvertex\fP * \fBb\fP"
.br
.ti -1c
.RI "int(* \fBf\fP )(void *, void *, const void *const, const void *const)"
.br
.ti -1c
.RI "void * \fBglbl\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBvertex\fP* edge_request::a"

.PP
Referenced by init(), procces_request(), setEdge(), and setupSelfEdge()\&.
.SS "struct \fBvertex\fP* edge_request::b"

.PP
Referenced by init(), procces_request(), setEdge(), and setupSelfEdge()\&.
.SS "int(* edge_request::f) (void *, void *, const void *const, const void *const)"

.PP
Referenced by init(), procces_request(), setEdge(), and setupSelfEdge()\&.
.SS "void* edge_request::glbl"

.PP
Referenced by init(), procces_request(), setEdge(), and setupSelfEdge()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
