.TH "testing/generate_graph_json_test.c" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing/generate_graph_json_test.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/topologic\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
References BI_EDGE, destroy_graph(), vertex::edge_tree, edge::edge_type, find(), parse_json(), print_graph(), and graph::vertices\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
