testing/graph_vertex_edge_test.c
NAME
testing/graph_vertex_edge_test.c
SYNOPSIS
#include '../include/topologic.h'
#include '../include/test.h'
Macros
#define TEST_SIZE 100
#define TEST_ARGC 3
Functions
void test_graph_insert_vertex (struct graph *)
void test_graph_add_edge (struct graph *)
void test_graph_add_bi_edge (struct graph *)
void test_graph_modify_vertex (struct graph *)
void test_graph_modify_edge (struct graph *)
void test_graph_modify_bi_edge (struct graph *)
void test_graph_remove_vertex (struct graph *)
void test_graph_remove_edge (struct graph *)
void test_graph_remove_bi_edge (struct graph *)
void testFunction (struct graph *graph, struct vertex_result *argv, void *glbl, void *edge_vars)
void testFunction2 (struct graph *graph, struct vertex_result *argv, void *glbl, void *edge_vars)
int testFuncEdge (void *args, void *glbl, const void *const edge_vars_a, const void *const edge_vars_b)
int testFuncEdge2 (void *args, void *glbl, const void *const edge_vars_a, const void *const edge_vars_b)
int main ()
Macro Definition Documentation
#define TEST_ARGC 3
#define TEST_SIZE 100
Function Documentation
int main ()
References destroy_graph(), GRAPH_INIT, test_graph_add_bi_edge(), test_graph_add_edge(), test_graph_insert_vertex(), test_graph_modify_bi_edge(), test_graph_modify_edge(), test_graph_modify_vertex(), test_graph_remove_bi_edge(), test_graph_remove_edge(), and test_graph_remove_vertex().
void test_graph_add_bi_edge (struct graph * graph)
References edge::a, edge::b, create_bi_edge(), edge::f, find(), edge::glbl, TEST_SIZE, testFuncEdge(), and graph::vertices.
Referenced by main().
void test_graph_add_edge (struct graph * graph)
References edge::a, edge::b, create_edge(), edge::f, find(), edge::glbl, TEST_SIZE, testFuncEdge(), and graph::vertices.
Referenced by main().
void test_graph_insert_vertex (struct graph * graph)
References create_vertex(), TEST_SIZE, and testFunction().
Referenced by main().
void test_graph_modify_bi_edge (struct graph * graph)
References find(), modify_bi_edge(), TEST_SIZE, testFuncEdge(), testFuncEdge2(), and graph::vertices.
Referenced by main().
void test_graph_modify_edge (struct graph * graph)
References find(), modify_edge(), TEST_SIZE, testFuncEdge(), testFuncEdge2(), and graph::vertices.
Referenced by main().
void test_graph_modify_vertex (struct graph * graph)
References find(), vertex::glbl, modify_vertex(), TEST_SIZE, testFunction(), testFunction2(), and graph::vertices.
Referenced by main().
void test_graph_remove_bi_edge (struct graph * graph)
References find(), remove_bi_edge(), TEST_SIZE, and graph::vertices.
Referenced by main().
void test_graph_remove_edge (struct graph * graph)
References vertex::edge_tree, find(), edge::glbl, vertex::id, remove_edge(), TEST_SIZE, and graph::vertices.
Referenced by main().
void test_graph_remove_vertex (struct graph * graph)
References find(), vertex::glbl, remove_vertex(), TEST_SIZE, and graph::vertices.
Referenced by main().
int testFuncEdge (void * args, void * glbl, const void *const edge_vars_a, const void *const edge_vars_b)
Referenced by test_graph_add_bi_edge(), test_graph_add_edge(), test_graph_modify_bi_edge(), and test_graph_modify_edge().
int testFuncEdge2 (void * args, void * glbl, const void *const edge_vars_a, const void *const edge_vars_b)
Referenced by test_graph_modify_bi_edge(), and test_graph_modify_edge().
void testFunction (struct graph * graph, struct vertex_result * argv, void * glbl, void * edge_vars)
Referenced by test_graph_insert_vertex(), and test_graph_modify_vertex().
void testFunction2 (struct graph * graph, struct vertex_result * argv, void * glbl, void * edge_vars)
References vertex_result::edge_argv, and vertex_result::vertex_argv.
Referenced by test_graph_modify_vertex().
Author
Generated automatically by Doxygen for Topologic from the source code.