src/graph.c
NAME
src/graph.c
SYNOPSIS
#include '../include/topologic.h'
Functions
struct graph * graph_init (int max_state_changes, int snapshot_timestamp, int max_loop, unsigned int lvl_verbose, enum CONTEXT context, enum MEM_OPTION mem_option)
void destroy_graph_stack (struct stack *stack)
void destroy_graph_avl (struct graph *graph, struct AVLTree *tree)
int destroy_graph (struct graph *graph)
Function Documentation
int destroy_graph (struct graph * graph)
@PARAM graph: the graph @RETURN -1 for fail; 0 for success Destroys and frees the graph
References graph::black_fire, graph::black_locked, graph::black_vertex_count, graph::color_lock, graph::context, destroy_graph_avl(), destroy_graph_stack(), graph::lock, graph::modify, graph::pause_cond, graph::red_fire, graph::red_locked, graph::red_vertex_count, graph::remove_edges, graph::remove_vertices, SINGLE, graph::start, graph::state, TERMINATE, topologic_debug, and graph::vertices.
Referenced by cleanup(), and main().
void destroy_graph_avl (struct graph * graph, struct AVLTree * tree)
References destroy_avl(), destroy_stack(), init_stack(), pop(), preorder(), and remove_vertex().
Referenced by destroy_graph().
void destroy_graph_stack (struct stack * stack)
References destroy_request(), destroy_stack(), and pop().
Referenced by destroy_graph().
struct graph* graph_init (int max_state_changes, int snapshot_timestamp, int max_loop, unsigned int lvl_verbose, enum CONTEXT context, enum MEM_OPTION mem_option)
@PARAM max_state_changes: # state changes before entering sink vertex due to infinite loop of states; -1 to ignore @PARAM snapshot_timestamp: printing out data at given timestamp for user; -1 for none; 0 for first and last state @PARAM lvl_verbose: how verbose timestamp print is @PARAM context: linear or context-switch based @RETURN an empty graph Creates a graph structures
References graph::black_fire, graph::black_locked, graph::black_vertex_count, graph::color_lock, graph::context, destroy_avl(), destroy_stack(), init_avl(), init_stack(), graph::lock, graph::lvl_verbose, graph::max_loop, graph::max_state_changes, graph::mem_option, graph::modify, NONE, graph::num_vertices, graph::pause, graph::pause_cond, graph::previous_color, graph::print_flag, RED, graph::red_fire, graph::red_locked, graph::red_vertex_count, graph::remove_edges, graph::remove_vertices, SINGLE, graph::snapshot_timestamp, graph::start, graph::state, graph::state_count, topologic_debug, and graph::vertices.
Referenced by init().
Author
Generated automatically by Doxygen for Topologic from the source code.