.TH "mod_edge_vars_request" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mod_edge_vars_request
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vertex\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBvertex\fP * \fBvertex\fP"
.br
.ti -1c
.RI "void * \fBedge_vars\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* mod_edge_vars_request::edge_vars"

.PP
Referenced by procces_request()\&.
.SS "struct \fBvertex\fP* mod_edge_vars_request::vertex"

.PP
Referenced by procces_request()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
