testing/multi_edge.c
NAME
testing/multi_edge.c
SYNOPSIS
#include '../include/topologic.h'
#include '../include/test.h'
Macros
#define MAXIMUM 6
Functions
void init (struct graph **)
void setupVertex (struct graph *)
void setupEdges (struct graph *)
void runTest (struct graph *)
void cleanup (struct graph *)
int edgeFunction (void *args, void *glbl, const void *const edge_vars_a, const void *const edge_vars_b)
void vertexFunction (struct graph *graph, struct vertex_result *args, void *glbl, void *edge_vars)
int main ()
void setEdge (struct graph *graph, struct vertex *a, struct vertex *b)
Macro Definition Documentation
#define MAXIMUM 6
Function Documentation
void cleanup (struct graph * graph)
References destroy_graph().
Referenced by main().
int edgeFunction (void * args, void * glbl, const void *const edge_vars_a, const void *const edge_vars_b)
Referenced by setEdge().
void init (struct graph ** graph)
References CONTINUE, EDGES, FUNCTIONS, GLOBALS, graph_init(), MAX_LOOPS, SINGLE, START_STOP, and VERTICES.
Referenced by main().
int main ()
References cleanup(), init(), runTest(), setupEdges(), and setupVertex().
void runTest (struct graph * graph)
References vertex_result::edge_argv, vertex_result::edge_size, run(), start_set(), vertex_result::vertex_argv, and vertex_result::vertex_size.
Referenced by main().
void setEdge (struct graph * graph, struct vertex * a, struct vertex * b)
References edge_request::a, edge_request::b, CREAT_BI_EDGE, create_request(), edgeFunction(), edge_request::f, edge_request::glbl, vertex::id, and submit_request().
Referenced by setupEdges().
void setupEdges (struct graph * graph)
References find(), MAXIMUM, process_requests(), setEdge(), and graph::vertices.
Referenced by main().
void setupVertex (struct graph * graph)
References CREAT_VERTEX, create_request(), vertex_request::f, vertex_request::glbl, vertex_request::graph, vertex_request::id, MAXIMUM, process_requests(), submit_request(), and vertexFunction().
Referenced by main().
void vertexFunction (struct graph * graph, struct vertex_result * args, void * glbl, void * edge_vars)
References vertex_result::edge_argv, and vertex_result::vertex_argv.
Referenced by setupVertex().
Author
Generated automatically by Doxygen for Topologic from the source code.