.TH "testing/multi_edge.c" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing/multi_edge.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/topologic\&.h'\fP
.br
\fC#include '\&.\&./include/test\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAXIMUM\fP   6"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (struct \fBgraph\fP **)"
.br
.ti -1c
.RI "void \fBsetupVertex\fP (struct \fBgraph\fP *)"
.br
.ti -1c
.RI "void \fBsetupEdges\fP (struct \fBgraph\fP *)"
.br
.ti -1c
.RI "void \fBrunTest\fP (struct \fBgraph\fP *)"
.br
.ti -1c
.RI "void \fBcleanup\fP (struct \fBgraph\fP *)"
.br
.ti -1c
.RI "int \fBedgeFunction\fP (void *args, void *glbl, const void *const edge_vars_a, const void *const edge_vars_b)"
.br
.ti -1c
.RI "void \fBvertexFunction\fP (struct \fBgraph\fP *\fBgraph\fP, struct \fBvertex_result\fP *args, void *glbl, void *edge_vars)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.ti -1c
.RI "void \fBsetEdge\fP (struct \fBgraph\fP *\fBgraph\fP, struct \fBvertex\fP *a, struct \fBvertex\fP *b)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAXIMUM   6"

.SH "Function Documentation"
.PP 
.SS "void cleanup (struct \fBgraph\fP * graph)"

.PP
References destroy_graph()\&.
.PP
Referenced by main()\&.
.SS "int edgeFunction (void * args, void * glbl, const void *const edge_vars_a, const void *const edge_vars_b)"

.PP
Referenced by setEdge()\&.
.SS "void init (struct \fBgraph\fP ** graph)"

.PP
References CONTINUE, EDGES, FUNCTIONS, GLOBALS, graph_init(), MAX_LOOPS, SINGLE, START_STOP, and VERTICES\&.
.PP
Referenced by main()\&.
.SS "int main ()"

.PP
References cleanup(), init(), runTest(), setupEdges(), and setupVertex()\&.
.SS "void runTest (struct \fBgraph\fP * graph)"

.PP
References vertex_result::edge_argv, vertex_result::edge_size, run(), start_set(), vertex_result::vertex_argv, and vertex_result::vertex_size\&.
.PP
Referenced by main()\&.
.SS "void setEdge (struct \fBgraph\fP * graph, struct \fBvertex\fP * a, struct \fBvertex\fP * b)"

.PP
References edge_request::a, edge_request::b, CREAT_BI_EDGE, create_request(), edgeFunction(), edge_request::f, edge_request::glbl, vertex::id, and submit_request()\&.
.PP
Referenced by setupEdges()\&.
.SS "void setupEdges (struct \fBgraph\fP * graph)"

.PP
References find(), MAXIMUM, process_requests(), setEdge(), and graph::vertices\&.
.PP
Referenced by main()\&.
.SS "void setupVertex (struct \fBgraph\fP * graph)"

.PP
References CREAT_VERTEX, create_request(), vertex_request::f, vertex_request::glbl, vertex_request::graph, vertex_request::id, MAXIMUM, process_requests(), submit_request(), and vertexFunction()\&.
.PP
Referenced by main()\&.
.SS "void vertexFunction (struct \fBgraph\fP * graph, struct \fBvertex_result\fP * args, void * glbl, void * edge_vars)"

.PP
References vertex_result::edge_argv, and vertex_result::vertex_argv\&.
.PP
Referenced by setupVertex()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
