.TH "include/request.h" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/request.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBrequest\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBREQUESTS\fP { \fBCREAT_VERTEX\fP = 0, \fBCREAT_EDGE\fP = 1, \fBCREAT_BI_EDGE\fP = 2, \fBMOD_VERTEX\fP = 3, \fBMOD_EDGE_VARS\fP = 4, \fBMOD_EDGE\fP = 5, \fBMOD_BI_EDGE\fP = 6, \fBDESTROY_VERTEX\fP = 7, \fBDESTROY_VERTEX_BY_ID\fP = 8, \fBDESTROY_EDGE\fP = 9, \fBDESTROY_BI_EDGE\fP = 10, \fBDESTROY_EDGE_BY_ID\fP = 11, \fBGENERIC\fP = 12 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBREQUESTS\fP"
Enum for submiting a request to be handles MODIFY: Modify values in existing edges or vertices as well as add vertices or edges DESTROY_VERTEX: Remove vertex from graph DESTROY_EDGE: Remove edge from graph 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICREAT_VERTEX \fP\fP
.TP
\fB\fICREAT_EDGE \fP\fP
.TP
\fB\fICREAT_BI_EDGE \fP\fP
.TP
\fB\fIMOD_VERTEX \fP\fP
.TP
\fB\fIMOD_EDGE_VARS \fP\fP
.TP
\fB\fIMOD_EDGE \fP\fP
.TP
\fB\fIMOD_BI_EDGE \fP\fP
.TP
\fB\fIDESTROY_VERTEX \fP\fP
.TP
\fB\fIDESTROY_VERTEX_BY_ID \fP\fP
.TP
\fB\fIDESTROY_EDGE \fP\fP
.TP
\fB\fIDESTROY_BI_EDGE \fP\fP
.TP
\fB\fIDESTROY_EDGE_BY_ID \fP\fP
.TP
\fB\fIGENERIC \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
