.TH "testing/request_test.c" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing/request_test.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/topologic\&.h'\fP
.br
\fC#include '\&.\&./include/test\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_VERTICES\fP   100"
.br
.ti -1c
.RI "#define \fBMAX_EDGES\fP   \fBMAX_VERTICES\fP"
.br
.ti -1c
.RI "#define \fBDEFAULT_BUFFER\fP   32"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (struct \fBgraph\fP **)"
.br
.ti -1c
.RI "void \fBtest_create_request\fP (struct \fBgraph\fP *)"
.br
.ti -1c
.RI "void \fBtest_submit_request\fP (struct \fBgraph\fP *)"
.br
.ti -1c
.RI "void \fBtest_process_requests\fP (struct \fBgraph\fP *)"
.br
.ti -1c
.RI "void \fBtest_destroy_request\fP (struct \fBgraph\fP *)"
.br
.ti -1c
.RI "void \fBcleanup\fP (struct \fBgraph\fP *)"
.br
.ti -1c
.RI "int \fBedgeFunction\fP (void *args, void *glbl, const void *const edge_vars_a, const void *const edge_vars_b)"
.br
.ti -1c
.RI "void \fBvertexFunction\fP (struct \fBgraph\fP *\fBgraph\fP, struct \fBvertex_result\fP *args, void *glbl, void *edge_vars)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFAULT_BUFFER   32"

.SS "#define MAX_EDGES   \fBMAX_VERTICES\fP"

.SS "#define MAX_VERTICES   100"

.SH "Function Documentation"
.PP 
.SS "void cleanup (struct \fBgraph\fP * graph)"

.PP
References destroy_graph(), find(), vertex::glbl, MAX_VERTICES, remove_vertex(), and graph::vertices\&.
.PP
Referenced by main()\&.
.SS "int edgeFunction (void * args, void * glbl, const void *const edge_vars_a, const void *const edge_vars_b)"

.SS "void init (struct \fBgraph\fP ** graph)"

.PP
References GRAPH_INIT\&.
.PP
Referenced by main()\&.
.SS "int main ()"

.PP
References cleanup(), init(), test_create_request(), test_destroy_request(), test_process_requests(), and test_submit_request()\&.
.SS "void test_create_request (struct \fBgraph\fP * graph)"

.PP
References CREAT_VERTEX, CREATE_REQUEST, vertex_request::f, request::f, vertex_request::glbl, vertex_request::graph, vertex_request::id, MAX_VERTICES, request::request, and vertexFunction()\&.
.PP
Referenced by main()\&.
.SS "void test_destroy_request (struct \fBgraph\fP * graph)"

.PP
References destroy_request(), graph::modify, pop(), graph::remove_edges, graph::remove_vertices, and request::request\&.
.PP
Referenced by main()\&.
.SS "void test_process_requests (struct \fBgraph\fP * graph)"

.PP
References process_requests()\&.
.PP
Referenced by main()\&.
.SS "void test_submit_request (struct \fBgraph\fP * graph)"

.PP
References CREAT_VERTEX, create_request(), vertex_request::f, vertex_request::glbl, vertex_request::graph, vertex_request::id, MAX_VERTICES, submit_request(), and vertexFunction()\&.
.PP
Referenced by main()\&.
.SS "void vertexFunction (struct \fBgraph\fP * graph, struct \fBvertex_result\fP * args, void * glbl, void * edge_vars)"

.PP
Referenced by test_create_request(), and test_submit_request()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
