testing/request_test.c
NAME
testing/request_test.c
SYNOPSIS
#include '../include/topologic.h'
#include '../include/test.h'
Macros
#define MAX_VERTICES 100
#define MAX_EDGES MAX_VERTICES
#define DEFAULT_BUFFER 32
Functions
void init (struct graph **)
void test_create_request (struct graph *)
void test_submit_request (struct graph *)
void test_process_requests (struct graph *)
void test_destroy_request (struct graph *)
void cleanup (struct graph *)
int edgeFunction (void *args, void *glbl, const void *const edge_vars_a, const void *const edge_vars_b)
void vertexFunction (struct graph *graph, struct vertex_result *args, void *glbl, void *edge_vars)
int main ()
Macro Definition Documentation
#define DEFAULT_BUFFER 32
#define MAX_EDGES MAX_VERTICES
#define MAX_VERTICES 100
Function Documentation
void cleanup (struct graph * graph)
References destroy_graph(), find(), vertex::glbl, MAX_VERTICES, remove_vertex(), and graph::vertices.
Referenced by main().
int edgeFunction (void * args, void * glbl, const void *const edge_vars_a, const void *const edge_vars_b)
void init (struct graph ** graph)
References GRAPH_INIT.
Referenced by main().
int main ()
References cleanup(), init(), test_create_request(), test_destroy_request(), test_process_requests(), and test_submit_request().
void test_create_request (struct graph * graph)
References CREAT_VERTEX, CREATE_REQUEST, vertex_request::f, request::f, vertex_request::glbl, vertex_request::graph, vertex_request::id, MAX_VERTICES, request::request, and vertexFunction().
Referenced by main().
void test_destroy_request (struct graph * graph)
References destroy_request(), graph::modify, pop(), graph::remove_edges, graph::remove_vertices, and request::request.
Referenced by main().
void test_process_requests (struct graph * graph)
References process_requests().
Referenced by main().
void test_submit_request (struct graph * graph)
References CREAT_VERTEX, create_request(), vertex_request::f, vertex_request::glbl, vertex_request::graph, vertex_request::id, MAX_VERTICES, submit_request(), and vertexFunction().
Referenced by main().
void vertexFunction (struct graph * graph, struct vertex_result * args, void * glbl, void * edge_vars)
Referenced by test_create_request(), and test_submit_request().
Author
Generated automatically by Doxygen for Topologic from the source code.