src/request.c
NAME
src/request.c
SYNOPSIS
#include '../include/topologic.h'
Functions
struct request * create_request (enum REQUESTS request, void *args, void(*f)(void *))
int submit_request (struct graph *graph, struct request *request)
int procces_request (struct request *request)
int process_requests (struct graph *graph)
int destroy_request (struct request *request)
Function Documentation
struct request* create_request (enum REQUESTS request, void * args, void(*)(void *) f)
@PARAM request: the desired request @PARAM args: the arguments needed for f @PARAM f: the function of the request @RETURN the request or NULL if it fails Creates a request structure to be called later
References request::args, CREAT_BI_EDGE, CREAT_EDGE, CREAT_VERTEX, DESTROY_BI_EDGE, DESTROY_EDGE, DESTROY_EDGE_BY_ID, DESTROY_VERTEX, DESTROY_VERTEX_BY_ID, request::f, GENERIC, MOD_BI_EDGE, MOD_EDGE, MOD_EDGE_VARS, MOD_VERTEX, request::request, and topologic_debug.
Referenced by init(), setEdge(), setupSelfEdge(), setupVertex(), test_submit_request(), and vertexFunction().
int destroy_request (struct request * request)
@PARAM request: a request @RETURN -1 for fail; 0 for success Destroys and frees a request
References request::args, request::f, request::request, and topologic_debug.
Referenced by destroy_graph_stack(), and test_destroy_request().
int procces_request (struct request * request)
References edge_request::a, destroy_edge_request::a, destroy_edge_id_request::a, request::args, edge_request::b, destroy_edge_request::b, CREAT_BI_EDGE, CREAT_EDGE, CREAT_VERTEX, create_bi_edge(), create_edge(), create_vertex(), DESTROY_BI_EDGE, DESTROY_EDGE, DESTROY_EDGE_BY_ID, DESTROY_VERTEX, DESTROY_VERTEX_BY_ID, mod_edge_vars_request::edge_vars, vertex_request::f, mod_vertex_request::f, request::f, edge_request::f, GENERIC, edge_request::glbl, vertex_request::glbl, mod_vertex_request::glbl, vertex_request::graph, destroy_vertex_request::graph, destroy_vertex_id_request::graph, destroy_edge_id_request::id, vertex_request::id, destroy_vertex_id_request::id, MOD_BI_EDGE, MOD_EDGE, MOD_EDGE_VARS, MOD_VERTEX, modify_bi_edge(), modify_edge(), modify_shared_edge_vars(), modify_vertex(), remove_bi_edge(), remove_edge(), remove_edge_id(), remove_vertex(), remove_vertex_id(), request::request, topologic_debug, mod_vertex_request::vertex, mod_edge_vars_request::vertex, and destroy_vertex_request::vertex.
Referenced by process_requests().
int process_requests (struct graph * graph)
@PARAM graph: the graph @RETURN 0 if all got processed; -1 if a request failed will set ERRNO to the ENUM Process requests that are queued in the graph
References graph::context, graph::lock, graph::modify, pop(), procces_request(), graph::remove_edges, graph::remove_vertices, SINGLE, and topologic_debug.
Referenced by init(), run(), run_single(), setupEdges(), setupSelfEdge(), setupVertex(), and test_process_requests().
int submit_request (struct graph * graph, struct request * request)
@PARAM graph: the graph @PARAM request: the request to be processed @RETRUN -1 for fail; 0 for succes; Submits a request to be processed after all active nodes complete
References graph::context, DESTROY_BI_EDGE, DESTROY_EDGE, DESTROY_EDGE_BY_ID, DESTROY_VERTEX, DESTROY_VERTEX_BY_ID, graph::lock, graph::modify, push(), graph::remove_edges, graph::remove_vertices, request::request, SINGLE, and topologic_debug.
Referenced by init(), setEdge(), setupSelfEdge(), setupVertex(), test_submit_request(), and vertexFunction().
Author
Generated automatically by Doxygen for Topologic from the source code.