testing/self_edge.c
NAME
testing/self_edge.c
SYNOPSIS
#include '../include/topologic.h'
#include '../include/test.h'
Macros
#define ONE 1
Functions
void init (struct graph **)
void setupSelfEdge (struct graph *)
void runTest (struct graph *)
void cleanup (struct graph *)
int edgeFunction (void *args, void *glbl, const void *const edge_vars_a, const void *const edge_vars_b)
void vertexFunction (struct graph *graph, struct vertex_result *args, void *glbl, void *edge_vars)
int main ()
Macro Definition Documentation
#define ONE 1
Function Documentation
void cleanup (struct graph * graph)
References destroy_graph().
Referenced by main().
int edgeFunction (void * args, void * glbl, const void *const edge_vars_a, const void *const edge_vars_b)
Referenced by setupSelfEdge().
void init (struct graph ** graph)
References CONTINUE, EDGES, FUNCTIONS, GLOBALS, graph_init(), NONE, START_STOP, and VERTICES.
Referenced by main().
int main ()
References cleanup(), init(), runTest(), and setupSelfEdge().
void runTest (struct graph * graph)
References vertex_result::edge_argv, vertex_result::edge_size, ONE, run(), vertex_result::vertex_argv, and vertex_result::vertex_size.
Referenced by main().
void setupSelfEdge (struct graph * graph)
References edge_request::a, edge_request::b, CREAT_EDGE, CREAT_VERTEX, create_request(), edgeFunction(), vertex_request::f, edge_request::f, find(), edge_request::glbl, vertex_request::glbl, vertex_request::graph, vertex_request::id, ONE, process_requests(), start_set(), submit_request(), and vertexFunction().
Referenced by main().
void vertexFunction (struct graph * graph, struct vertex_result * args, void * glbl, void * edge_vars)
References vertex_result::edge_argv, and vertex_result::vertex_argv.
Referenced by setupSelfEdge().
Author
Generated automatically by Doxygen for Topologic from the source code.