.TH "shared_edge" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shared_edge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vertex\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBvertex_data\fP"
.br
.ti -1c
.RI "const void *const  * \fBedge_data\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "const void* const* shared_edge::edge_data"

.PP
Referenced by create_edge()\&.
.SS "void* shared_edge::vertex_data"

.PP
Referenced by create_vertex(), fire(), modify_shared_edge_vars(), remove_vertex(), and run_single()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
