testing/stack_test.c
NAME
testing/stack_test.c
SYNOPSIS
#include '../include/stack.h'
#include '../include/test.h'
Macros
#define VALUE 10
Functions
void test_push (struct stack *stack)
void test_pop (struct stack *stack)
void test_pop_all (struct stack *stack)
void test_get (struct stack *stack)
int main ()
Macro Definition Documentation
#define VALUE 10
Function Documentation
int main ()
References destroy_stack(), init_stack(), test_pop(), test_pop_all(), and test_push().
void test_get (struct stack * stack)
References get(), and push().
void test_pop (struct stack * stack)
References pop(), and VALUE.
Referenced by main().
void test_pop_all (struct stack * stack)
References stack::length, pop(), and push().
Referenced by main().
void test_push (struct stack * stack)
References push(), and VALUE.
Referenced by main().
Author
Generated automatically by Doxygen for Topologic from the source code.