include/stack.h
NAME
include/stack.h
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
Data Structures
struct stack_node
struct stack
Functions
struct stack * init_stack ()
void * get (struct stack *stack, int index)
void * pop (struct stack *stack)
int push (struct stack *stack, void *data)
void destroy_stack (struct stack *stack)
Function Documentation
void destroy_stack (struct stack * stack)
References stack_node::data, stack::length, stack_node::next, and stack::root.
Referenced by destroy_graph_avl(), destroy_graph_stack(), fire(), graph_init(), main(), print_edges(), print_state(), remove_vertex(), run_single(), test_delete(), and test_inorder().
void* get (struct stack * stack, int index)
References stack_node::data, stack::length, stack_node::next, and stack::root.
Referenced by test_get().
struct stack* init_stack ()
References stack::length, and stack::root.
Referenced by destroy_graph_avl(), fire(), graph_init(), main(), print_edges(), print_state(), remove_vertex(), run_single(), test_delete(), and test_inorder().
void* pop (struct stack * stack)
References stack_node::data, stack::length, stack_node::next, and stack::root.
Referenced by destroy_graph_avl(), destroy_graph_stack(), fire(), print_edges(), print_state(), process_requests(), remove_vertex(), run(), run_single(), start_set(), test_delete(), test_destroy_request(), test_inorder(), test_pop(), and test_pop_all().
int push (struct stack * stack, void * data)
References stack_node::data, stack::length, stack_node::next, and stack::root.
Referenced by inorder_nodes(), postorder_nodes(), preorder_nodes(), stackify_nodes(), start_set(), submit_request(), test_get(), test_pop_all(), and test_push().
Author
Generated automatically by Doxygen for Topologic from the source code.