.TH "stack_node" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stack_node
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stack\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "struct \fBstack_node\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* stack_node::data"

.PP
Referenced by destroy_stack(), get(), pop(), and push()\&.
.SS "struct \fBstack_node\fP* stack_node::next"

.PP
Referenced by destroy_stack(), get(), pop(), and push()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
