.TH "testing/stack_test.c" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing/stack_test.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/stack\&.h'\fP
.br
\fC#include '\&.\&./include/test\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVALUE\fP   10"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_push\fP (struct \fBstack\fP *\fBstack\fP)"
.br
.ti -1c
.RI "void \fBtest_pop\fP (struct \fBstack\fP *\fBstack\fP)"
.br
.ti -1c
.RI "void \fBtest_pop_all\fP (struct \fBstack\fP *\fBstack\fP)"
.br
.ti -1c
.RI "void \fBtest_get\fP (struct \fBstack\fP *\fBstack\fP)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define VALUE   10"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
References destroy_stack(), init_stack(), test_pop(), test_pop_all(), and test_push()\&.
.SS "void test_get (struct \fBstack\fP * stack)"

.PP
References get(), and push()\&.
.SS "void test_pop (struct \fBstack\fP * stack)"

.PP
References pop(), and VALUE\&.
.PP
Referenced by main()\&.
.SS "void test_pop_all (struct \fBstack\fP * stack)"

.PP
References stack::length, pop(), and push()\&.
.PP
Referenced by main()\&.
.SS "void test_push (struct \fBstack\fP * stack)"

.PP
References push(), and VALUE\&.
.PP
Referenced by main()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
