.TH "stack" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stack
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stack\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBstack_node\fP * \fBroot\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int stack::length"

.PP
Referenced by destroy_stack(), get(), init_stack(), pop(), print_edges(), print_state(), push(), run_single(), and test_pop_all()\&.
.SS "struct \fBstack_node\fP* stack::root"

.PP
Referenced by destroy_stack(), get(), init_stack(), pop(), and push()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
