.TH "testing/switch_context_test.c" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing/switch_context_test.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/topologic\&.h'\fP
.br
\fC#include '\&.\&./include/test\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAXIMUM\fP   40"
.br
.ti -1c
.RI "#define \fBDEFAULT_BUFFER\fP   64"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (struct \fBgraph\fP **)"
.br
.ti -1c
.RI "void \fBsetup_start_set\fP (struct \fBgraph\fP *\fBgraph\fP)"
.br
.ti -1c
.RI "void \fBsetup_non_start_set\fP (struct \fBgraph\fP *\fBgraph\fP)"
.br
.ti -1c
.RI "void \fBtest_run_switch\fP (struct \fBgraph\fP *)"
.br
.ti -1c
.RI "void \fBcleanup\fP (struct \fBgraph\fP *)"
.br
.ti -1c
.RI "void \fBrequest_nil\fP ()"
.br
.ti -1c
.RI "int \fBedgeFunction\fP (void *args, void *glbl, const void *const edge_vars_a, const void *const edge_vars_b)"
.br
.ti -1c
.RI "void \fBvertexFunction\fP (struct \fBgraph\fP *\fBgraph\fP, struct \fBvertex_result\fP *args, void *glbl, void *edge_vars)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFAULT_BUFFER   64"

.SS "#define MAXIMUM   40"

.SH "Function Documentation"
.PP 
.SS "void cleanup (struct \fBgraph\fP * graph)"

.PP
References destroy_graph(), vertex::edge_tree, find(), edge::glbl, vertex::glbl, vertex::id, MAXIMUM, remove_edge(), remove_vertex(), and graph::vertices\&.
.PP
Referenced by main()\&.
.SS "int edgeFunction (void * args, void * glbl, const void *const edge_vars_a, const void *const edge_vars_b)"

.PP
Referenced by init()\&.
.SS "void init (struct \fBgraph\fP ** graph)"

.PP
References edge_request::a, edge_request::b, CONTINUE, CREAT_EDGE, CREAT_VERTEX, create_request(), edgeFunction(), EDGES, vertex::f, vertex_request::f, edge_request::f, find(), FUNCTIONS, edge_request::glbl, vertex_request::glbl, GLOBALS, vertex_request::graph, graph_init(), vertex_request::id, MAXIMUM, process_requests(), START_STOP, submit_request(), SWITCH, vertexFunction(), and VERTICES\&.
.PP
Referenced by main()\&.
.SS "int main ()"

.PP
References cleanup(), init(), setup_start_set(), and test_run_switch()\&.
.SS "void request_nil ()"

.PP
Referenced by vertexFunction()\&.
.SS "void setup_non_start_set (struct \fBgraph\fP * graph)"

.SS "void setup_start_set (struct \fBgraph\fP * graph)"

.PP
References start_set()\&.
.PP
Referenced by main()\&.
.SS "void test_run_switch (struct \fBgraph\fP * graph)"

.PP
References vertex_result::edge_argv, vertex_result::edge_size, run(), vertex_result::vertex_argv, and vertex_result::vertex_size\&.
.PP
Referenced by main()\&.
.SS "void vertexFunction (struct \fBgraph\fP * graph, struct \fBvertex_result\fP * args, void * glbl, void * edge_vars)"

.PP
References create_request(), vertex_result::edge_argv, GENERIC, request_nil(), and submit_request()\&.
.PP
Referenced by init()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
