testing/switch_context_test.c
NAME
testing/switch_context_test.c
SYNOPSIS
#include '../include/topologic.h'
#include '../include/test.h'
Macros
#define MAXIMUM 40
#define DEFAULT_BUFFER 64
Functions
void init (struct graph **)
void setup_start_set (struct graph *graph)
void setup_non_start_set (struct graph *graph)
void test_run_switch (struct graph *)
void cleanup (struct graph *)
void request_nil ()
int edgeFunction (void *args, void *glbl, const void *const edge_vars_a, const void *const edge_vars_b)
void vertexFunction (struct graph *graph, struct vertex_result *args, void *glbl, void *edge_vars)
int main ()
Macro Definition Documentation
#define DEFAULT_BUFFER 64
#define MAXIMUM 40
Function Documentation
void cleanup (struct graph * graph)
References destroy_graph(), vertex::edge_tree, find(), edge::glbl, vertex::glbl, vertex::id, MAXIMUM, remove_edge(), remove_vertex(), and graph::vertices.
Referenced by main().
int edgeFunction (void * args, void * glbl, const void *const edge_vars_a, const void *const edge_vars_b)
Referenced by init().
void init (struct graph ** graph)
References edge_request::a, edge_request::b, CONTINUE, CREAT_EDGE, CREAT_VERTEX, create_request(), edgeFunction(), EDGES, vertex::f, vertex_request::f, edge_request::f, find(), FUNCTIONS, edge_request::glbl, vertex_request::glbl, GLOBALS, vertex_request::graph, graph_init(), vertex_request::id, MAXIMUM, process_requests(), START_STOP, submit_request(), SWITCH, vertexFunction(), and VERTICES.
Referenced by main().
int main ()
References cleanup(), init(), setup_start_set(), and test_run_switch().
void request_nil ()
Referenced by vertexFunction().
void setup_non_start_set (struct graph * graph)
void setup_start_set (struct graph * graph)
References start_set().
Referenced by main().
void test_run_switch (struct graph * graph)
References vertex_result::edge_argv, vertex_result::edge_size, run(), vertex_result::vertex_argv, and vertex_result::vertex_size.
Referenced by main().
void vertexFunction (struct graph * graph, struct vertex_result * args, void * glbl, void * edge_vars)
References create_request(), vertex_result::edge_argv, GENERIC, request_nil(), and submit_request().
Referenced by init().
Author
Generated automatically by Doxygen for Topologic from the source code.