include/topologic.h
NAME
include/topologic.h
SYNOPSIS
#include './header.h'
#include './stack.h'
#include './AVL.h'
#include './edge.h'
#include './vertex.h'
#include './request.h'
#include './graph.h'
Data Structures
struct fireable
Macros
#define PTHREAD_SLEEP_TIME 50
#define _GNU_SOURCE
#define TOPOLOGIC_DEBUG 0
#define topologic_debug(fmt, ...)
#define MAX_LOOPS 100
#define GRAPH_INIT() graph_init(-1, START_STOP, MAX_LOOPS, VERTICES | EDGES | FUNCTIONS | GLOBALS, SINGLE, CONTINUE)
#define CREATE_VERTEX(graph, f, id) create_vertex(graph, f, id, NULL, PROTECT_B_VARS)
#define CREATE_VERTEX_GLBL(graph, f, id, glbl) create_vertex(graph, f, id, glbl, PROTECT_B_VARS)
#define CREATE_EDGE(a, b, f) create_edge(a, b, f, NULL)
#define CREATE_NULL_BI_EDGE(a, b, f) create_bi_edge(a, b, f, NULL, NULL, NULL)
#define CREATE_BI_EDGE(a, b, f, a_to_b, b_to_a) create_bi_edge(a, b, f, NULL, a_to_b, b_to_a)
#define MODIFY_VERTEX(vertex, f) modify_vertex(vertex, f, NULL)
#define MODIFY_VERTEX_GLOBALS(vertex, glbl) modify_vertex(vertex, NULL, glbl)
#define MODIFY_EDGE(a, b, f) modify_edge(a, b, f, NULL)
#define MODIFY_EDGE_GLOBALS(a, b, glbl) modify_edge(a, b, NULL, glbl)
#define MODIFY_BI_EDGE(a, b, f) modify_bi_edge(a, b, f, NULL)
#define MODIFY_BI_EDGE_GLOBALS(a, b, glbl) modify_bi_edge(a, b, NULL, glbl)
#define CREATE_REQUEST(request, args) create_request(request, args, NULL)
Functions
void * fire_pthread (void *vargp)
struct graph * graph_init (int max_state_changes, int snapshot_timestamp, int max_loop, unsigned int lvl_verbose, enum CONTEXT context, enum MEM_OPTION mem_option)
struct vertex * create_vertex (struct graph *graph, void(*f)(struct graph *, struct vertex_result *, void *, void *), int id, void *glbl)
struct edge * create_edge (struct vertex *a, struct vertex *b, int(*f)(void *, void *, const void *const, const void *const), void *glbl)
int create_bi_edge (struct vertex *a, struct vertex *b, int(*f)(void *, void *, const void *const, const void *const), void *glbl, struct edge **edge_a_to_b, struct edge **edge_b_to_a)
int remove_edge (struct vertex *a, struct vertex *b)
int remove_edge_id (struct vertex *a, int id)
int remove_bi_edge (struct vertex *a, struct vertex *b)
int remove_vertex (struct graph *graph, struct vertex *vertex)
int remove_vertex_id (struct graph *graph, int id)
int modify_vertex (struct vertex *vertex, void(*f)(struct graph *, struct vertex_result *, void *, void *), void *glbl)
int modify_shared_edge_vars (struct vertex *vertex, void *edge_vars)
int modify_edge (struct vertex *a, struct vertex *b, int(*f)(void *, void *, const void *const, const void *const), void *glbl)
int modify_bi_edge (struct vertex *a, struct vertex *b, int(*f)(void *, void *, const void *const, const void *const), void *glbl)
int fire (struct graph *graph, struct vertex *vertex, struct vertex_result *args, enum STATES color, int iloop)
int switch_vertex (struct graph *graph, struct vertex *vertex, struct vertex_result *args, enum STATES color, int iloop)
int start_set (struct graph *graph, int id[], int num_vertices)
int submit_request (struct graph *, struct request *request)
struct request * create_request (enum REQUESTS request, void *args, void(*f)(void *))
int process_requests (struct graph *graph)
int run (struct graph *graph, struct vertex_result **vertex_args)
int resume_graph (struct graph *graph)
int pause_graph (struct graph *graph)
void print_graph (struct graph *graph)
struct graph * parse_json (const char *path)
int destroy_graph (struct graph *graph)
int destroy_request (struct request *request)
Macro Definition Documentation
#define _GNU_SOURCE
#define CREATE_BI_EDGE(a, b, f, a_to_b, b_to_a) create_bi_edge(a, b, f, NULL, a_to_b, b_to_a)
#define CREATE_EDGE(a, b, f) create_edge(a, b, f, NULL)
#define CREATE_NULL_BI_EDGE(a, b, f) create_bi_edge(a, b, f, NULL, NULL, NULL)
#define CREATE_REQUEST(request, args) create_request(request, args, NULL)
#define CREATE_VERTEX(graph, f, id) create_vertex(graph, f, id, NULL, PROTECT_B_VARS)
#define CREATE_VERTEX_GLBL(graph, f, id, glbl) create_vertex(graph, f, id, glbl, PROTECT_B_VARS)
#define GRAPH_INIT() graph_init(-1, START_STOP, MAX_LOOPS, VERTICES | EDGES | FUNCTIONS | GLOBALS, SINGLE, CONTINUE)
#define MAX_LOOPS 100
#define MODIFY_BI_EDGE(a, b, f) modify_bi_edge(a, b, f, NULL)
#define MODIFY_BI_EDGE_GLOBALS(a, b, glbl) modify_bi_edge(a, b, NULL, glbl)
#define MODIFY_EDGE(a, b, f) modify_edge(a, b, f, NULL)
#define MODIFY_EDGE_GLOBALS(a, b, glbl) modify_edge(a, b, NULL, glbl)
#define MODIFY_VERTEX(vertex, f) modify_vertex(vertex, f, NULL)
#define MODIFY_VERTEX_GLOBALS(vertex, glbl) modify_vertex(vertex, NULL, glbl)
#define PTHREAD_SLEEP_TIME 50
#define TOPOLOGIC_DEBUG 0
#define topologic_debug(fmt, ...)
Value:
                                                                   do {if (TOPOLOGIC_DEBUG) fprintf(stderr, "%s:%s:%s:%d:%s(): " fmt "\n", __DATE__, __TIME__, \
                                                                   __FILE__, __LINE__, __func__, __VA_ARGS__); } while (0)
Function Documentation
int create_bi_edge (struct vertex * a, struct vertex * b, int(*)(void *, void *, const void *const, const void *const) f, void * glbl, struct edge ** edge_a_to_b, struct edge ** edge_b_to_a)
@RETURNS 0 for success; -1 for fail See create_edge Will create an bidirectional edge between vertex a and b with some criteria determined by the function f. Will store the edges in edge_a and edge_b. If edge_a_to_b or edge_b_to_a is NULL it will not.
References edge::a, edge::b, BI_EDGE, edge::bi_edge, edge::bi_edge_lock, vertex::context, create_edge(), edge::edge_type, edge::f, edge::glbl, remove_edge(), SINGLE, and topologic_debug.
Referenced by procces_request(), and test_graph_add_bi_edge().
struct edge* create_edge (struct vertex * a, struct vertex * b, int(*)(void *, void *, const void *const, const void *const) f, void * glbl)
@PARAM a: A vertex @PARAM b: Another vertex (can be 'a') @PARAM f: a function @PARAM glbl: global variables @RETURN the edge connecting a to b Will create an edge from vertex a to b with some criteria determined by the function f. NOTE: NULL glbl will mean no global variables. f cannot be NULL.
References edge::a, edge::a_vars, edge::b, edge::b_vars, edge::bi_edge, vertex::context, EDGE, shared_edge::edge_data, vertex::edge_tree, edge::edge_type, edge::f, find(), edge::glbl, edge::id, vertex::id, insert(), vertex::joining_vertices, vertex::lock, remove_edge(), remove_ID(), SELF_EDGE, vertex::shared, SINGLE, SWITCH, and topologic_debug.
Referenced by create_bi_edge(), procces_request(), and test_graph_add_edge().
struct request* create_request (enum REQUESTS request, void * args, void(*)(void *) f)
@PARAM request: the desired request @PARAM args: the arguments needed for f @PARAM f: the function of the request @RETURN the request or NULL if it fails Creates a request structure to be called later
References request::args, CREAT_BI_EDGE, CREAT_EDGE, CREAT_VERTEX, DESTROY_BI_EDGE, DESTROY_EDGE, DESTROY_EDGE_BY_ID, DESTROY_VERTEX, DESTROY_VERTEX_BY_ID, request::f, GENERIC, MOD_BI_EDGE, MOD_EDGE, MOD_EDGE_VARS, MOD_VERTEX, request::request, and topologic_debug.
Referenced by init(), setEdge(), setupSelfEdge(), setupVertex(), test_submit_request(), and vertexFunction().
struct vertex* create_vertex (struct graph * graph, void(*)(struct graph *, struct vertex_result *, void *, void *) f, int id, void * glbl)
@PARAM graph: the graph @PARAM f: a function @PARAM id: vertex id to be used: MUST BE UNIQUE @PARAM glbl: global variables @RETURN vertex: a vertex to be used in a graph On creation a process will be spawned for the vertex The vertex will compute function f when called NOTE: NULL glbl will mean no global variables. f cannot be NULL.
References graph::context, vertex::context, destroy_avl(), vertex::edge_tree, vertex::f, vertex::glbl, vertex::id, init_avl(), insert(), vertex::is_active, vertex::joining_vertices, graph::lock, vertex::lock, vertex::shared, SINGLE, topologic_debug, shared_edge::vertex_data, and graph::vertices.
Referenced by procces_request(), and test_graph_insert_vertex().
int destroy_graph (struct graph * graph)
@PARAM graph: the graph @RETURN -1 for fail; 0 for success Destroys and frees the graph
References graph::black_fire, graph::black_locked, graph::black_vertex_count, graph::color_lock, graph::context, destroy_graph_avl(), destroy_graph_stack(), graph::lock, graph::modify, graph::pause_cond, graph::red_fire, graph::red_locked, graph::red_vertex_count, graph::remove_edges, graph::remove_vertices, SINGLE, graph::start, graph::state, TERMINATE, topologic_debug, and graph::vertices.
Referenced by cleanup(), and main().
int destroy_request (struct request * request)
@PARAM request: a request @RETURN -1 for fail; 0 for success Destroys and frees a request
References request::args, request::f, request::request, and topologic_debug.
Referenced by destroy_graph_stack(), and test_destroy_request().
int fire (struct graph * graph, struct vertex * vertex, struct vertex_result * args, enum STATES color, int iloop)
@PARAM graph: the graph @PARAM vertex: A vertex to be ran @PARAM args: arguments @PARAM color: the state in which unlocks fire process if STATE is set to PRINT then fire will fail @PARAM iloop: the number of times that vertex fired in succession @RETURNS the result of the vertex fire will wake up the vertex and pass args to the vertex to compute its function and then call switch and clean itself up
References edge::a_vars, fireable::args, edge::b, edge::b_vars, BI_EDGE, edge::bi_edge_lock, BLACK, graph::black_fire, graph::black_locked, graph::black_vertex_count, fireable::color, graph::context, destroy_stack(), vertex_result::edge_argv, vertex::edge_tree, edge::edge_type, vertex::f, edge::f, fire(), edge::glbl, vertex::glbl, fireable::iloop, init_stack(), vertex::is_active, graph::lock, vertex::lock, graph::max_loop, graph::max_state_changes, NONE, graph::num_vertices, pop(), preorder(), PTHREAD_SLEEP_TIME, RED, graph::red_fire, graph::red_locked, graph::red_vertex_count, vertex::shared, sleep_ms(), graph::state, graph::state_count, SWITCH, SWITCH_UNSAFE, switch_vertex(), TERMINATE, topologic_debug, vertex_result::vertex_argv, and shared_edge::vertex_data.
Referenced by fire(), and fire_pthread().
void* fire_pthread (void * vargp)
Wrapper function for fire, fire_1 @PARAM vargp: arguments
References fireable::args, fireable::color, fire(), fireable::graph, fireable::iloop, PTHREAD_SLEEP_TIME, sleep_ms(), topologic_debug, and fireable::vertex.
Referenced by run(), and switch_vertex().
struct graph* graph_init (int max_state_changes, int snapshot_timestamp, int max_loop, unsigned int lvl_verbose, enum CONTEXT context, enum MEM_OPTION mem_option)
@PARAM max_state_changes: # state changes before entering sink vertex due to infinite loop of states; -1 to ignore @PARAM snapshot_timestamp: printing out data at given timestamp for user; -1 for none; 0 for first and last state @PARAM lvl_verbose: how verbose timestamp print is @PARAM context: linear or context-switch based @RETURN an empty graph Creates a graph structures
References graph::black_fire, graph::black_locked, graph::black_vertex_count, graph::color_lock, graph::context, destroy_avl(), destroy_stack(), init_avl(), init_stack(), graph::lock, graph::lvl_verbose, graph::max_loop, graph::max_state_changes, graph::mem_option, graph::modify, NONE, graph::num_vertices, graph::pause, graph::pause_cond, graph::previous_color, graph::print_flag, RED, graph::red_fire, graph::red_locked, graph::red_vertex_count, graph::remove_edges, graph::remove_vertices, SINGLE, graph::snapshot_timestamp, graph::start, graph::state, graph::state_count, topologic_debug, and graph::vertices.
Referenced by init().
int modify_bi_edge (struct vertex * a, struct vertex * b, int(*)(void *, void *, const void *const, const void *const) f, void * glbl)
@PARAM a: a vertex @PARAM b: another vertex @PARAM f: a function @PARAM glbl: global variables @RETURN 0 for success; -1 for fail; -2 if only edge from a to b is modified; -3 if only edge from b to a is modified Modifies the edge between a and b's function and variables NOTE: NULL f, or glbl will mean no change.
References edge::a, edge::b, edge::f, edge::glbl, modify_edge(), and topologic_debug.
Referenced by procces_request(), and test_graph_modify_bi_edge().
int modify_edge (struct vertex * a, struct vertex * b, int(*)(void *, void *, const void *const, const void *const) f, void * glbl)
@PARAM a: a vertex @PARAM b: another vertex @PARAM f: a function @PARAM glbl: global variables @RETURN 0 for success; -1 for fail Modifies the edge connecting a to b's function NOTE: NULL f, or glbl will mean no change.
References edge::a, edge::b, vertex::context, vertex::edge_tree, edge::f, find(), edge::glbl, vertex::id, vertex::lock, SINGLE, and topologic_debug.
Referenced by modify_bi_edge(), procces_request(), and test_graph_modify_edge().
int modify_shared_edge_vars (struct vertex * vertex, void * edge_vars)
@PARAM vertex: a vertex @PARAM edge_vars: shared variables @RETURN 0 for success; -1 for fail Modifies the vertices shared variables with it's edges
References vertex::context, vertex::lock, vertex::shared, SINGLE, topologic_debug, and shared_edge::vertex_data.
Referenced by procces_request().
int modify_vertex (struct vertex * vertex, void(*)(struct graph *, struct vertex_result *, void *, void *) f, void * glbl)
@PARAM vertex: a vertex @PARAM f: a function @PARAM glbl: global variables NOTE: NULL f, or glbl will mean no change. @RETURN 0 for success; -1 for fail Modifies the vertices function
References vertex::context, vertex::f, vertex::glbl, vertex::lock, SINGLE, and topologic_debug.
Referenced by procces_request(), and test_graph_modify_vertex().
struct graph* parse_json (const char * path)
@PARAM path: path to graph input file @RETURN the graph specified in the file
Referenced by main().
int pause_graph (struct graph * graph)
@PARAM graph: the graph @RETURN 0 for success -1 if it fails Pauses run
References graph::lock, graph::pause, graph::pause_cond, and topologic_debug.
void print_graph (struct graph * graph)
@PARAM graph: the graph Prints the graph with desired output TODO: Print enums
References graph::context, graph::lock, graph::lvl_verbose, graph::max_loop, graph::max_state_changes, NO_VERB, graph::num_vertices, print_state(), SINGLE, AVLTree::size, graph::snapshot_timestamp, START_STOP, graph::state_count, topologic_debug, and graph::vertices.
Referenced by main(), run(), and run_single().
int process_requests (struct graph * graph)
@PARAM graph: the graph @RETURN 0 if all got processed; -1 if a request failed will set ERRNO to the ENUM Process requests that are queued in the graph
References graph::context, graph::lock, graph::modify, pop(), procces_request(), graph::remove_edges, graph::remove_vertices, SINGLE, and topologic_debug.
Referenced by init(), run(), run_single(), setupEdges(), setupSelfEdge(), setupVertex(), and test_process_requests().
int remove_bi_edge (struct vertex * a, struct vertex * b)
@PARAM a: a vertex @PARAM b: another vertex @RETURN 0 for success; -1 for fail; -2 if only edge from a to b is removed; -3 if only edge from b to a is removed Removes the edge connecting a to b
References edge::a, edge::b, remove_edge(), and topologic_debug.
Referenced by procces_request(), and test_graph_remove_bi_edge().
int remove_edge (struct vertex * a, struct vertex * b)
@PARAM a: a vertex @PARAM b: another vertex @RETURN 0 for success; -1 for fail Removes the edge connecting a to b
References edge::a, edge::a_vars, edge::b, edge::b_vars, BI_EDGE, edge::bi_edge, edge::bi_edge_lock, vertex::context, EDGE, vertex::edge_tree, edge::edge_type, edge::f, edge::glbl, edge::id, vertex::id, vertex::joining_vertices, vertex::lock, remove_ID(), SINGLE, and topologic_debug.
Referenced by cleanup(), create_bi_edge(), create_edge(), procces_request(), remove_bi_edge(), and test_graph_remove_edge().
int remove_edge_id (struct vertex * a, int id)
@PARAM a: a vertex @PARAM id: id of edge to remove @RETURN 0 for success; -1 for fail Removes the edge in a with that id
References edge::a, edge::a_vars, edge::b, edge::b_vars, BI_EDGE, edge::bi_edge, edge::bi_edge_lock, vertex::context, EDGE, vertex::edge_tree, edge::edge_type, edge::f, edge::glbl, edge::id, vertex::id, vertex::joining_vertices, vertex::lock, remove_ID(), SINGLE, and topologic_debug.
Referenced by procces_request(), and remove_vertex().
int remove_vertex (struct graph * graph, struct vertex * vertex)
@PARAM graph: the graph @PARAM vertex: a vertex @RETURN 0 for sucess; -1 for fail Removes the vertex and all connected edges
References edge::a, edge::b, BI_EDGE, edge::bi_edge, edge::bi_edge_lock, graph::context, vertex::context, destroy_stack(), EDGE, vertex::edge_tree, edge::edge_type, edge::f, edge::glbl, vertex::glbl, edge::id, vertex::id, init_stack(), vertex::joining_vertices, graph::lock, vertex::lock, pop(), remove_edge_id(), remove_ID(), SELF_EDGE, vertex::shared, SINGLE, stackify(), topologic_debug, shared_edge::vertex_data, and graph::vertices.
Referenced by cleanup(), destroy_graph_avl(), procces_request(), remove_vertex_id(), and test_graph_remove_vertex().
int remove_vertex_id (struct graph * graph, int id)
@PARAM graph: the graph @PARAM id: the vertex id @RETURN 0 for sucess; -1 for fail Removes the vertex and all connected edges
References graph::context, find(), graph::lock, remove_vertex(), SINGLE, topologic_debug, and graph::vertices.
Referenced by procces_request().
int resume_graph (struct graph * graph)
@PARAM graph: the graph @RETURN 0 for success -1 if it fails Resumes run
References graph::lock, graph::pause, and topologic_debug.
int run (struct graph * graph, struct vertex_result ** vertex_args)
@PARAM graph: the graph @PARAM vertex_args: array of vertex arguments for f @RETURN 0 if run terminates normally -1 if it fails Attempts to run the graph else aborts.
References ABORT, fireable::args, BLACK, graph::black_fire, graph::black_locked, graph::black_vertex_count, fireable::color, graph::color_lock, graph::context, CONTINUE, fire_pthread(), fireable::graph, fireable::iloop, vertex::is_active, graph::lock, MAX_ATTEMPTS, graph::max_state_changes, graph::mem_option, graph::num_vertices, graph::pause, graph::pause_cond, pop(), graph::previous_color, PRINT, graph::print_flag, print_graph(), process_requests(), RED, graph::red_fire, graph::red_locked, graph::red_vertex_count, run_single(), SINGLE, graph::start, graph::state, graph::state_count, TERMINATE, THREAD_ATTEMPT_SLEEP, topologic_debug, fireable::vertex, and WAIT.
Referenced by runTest(), test_run_none(), test_run_single(), and test_run_switch().
int start_set (struct graph * graph, int id[], int num_vertices)
@PARAM graph: the graph, @PARAM id: the ids of the vertices @PARAM num_vertices: number of vertices @RETURN -1 for fail if any vertex fails; 0 for success Creates multiple contexts that are ran in parallel Handle errors
Given vertx failed, so at this point, free the vertices and leave
References graph::context, find(), vertex::id, pop(), push(), SINGLE, graph::start, topologic_debug, and graph::vertices.
Referenced by runTest(), setup_start_set(), and setupSelfEdge().
int submit_request (struct graph * graph, struct request * request)
@PARAM graph: the graph @PARAM request: the request to be processed @RETRUN -1 for fail; 0 for succes; Submits a request to be processed after all active nodes complete
References graph::context, DESTROY_BI_EDGE, DESTROY_EDGE, DESTROY_EDGE_BY_ID, DESTROY_VERTEX, DESTROY_VERTEX_BY_ID, graph::lock, graph::modify, push(), graph::remove_edges, graph::remove_vertices, request::request, SINGLE, and topologic_debug.
Referenced by init(), setEdge(), setupSelfEdge(), setupVertex(), test_submit_request(), and vertexFunction().
int switch_vertex (struct graph * graph, struct vertex * vertex, struct vertex_result * args, enum STATES color, int iloop)
@PARAM graph: the graph @PARAM vertex: The vertex in which just fire @PARAM args; The result of the vertex Upon call the switch function will compute the edge functions connected to the vertex @PARAM iloop: the number of times that vertex fired in succession @RETURNS 0 On success; the vertex connected to the successful edge will be fired; -1 on failure
References ABORT, fireable::args, fireable::color, CONTINUE, vertex_result::edge_argv, vertex_result::edge_size, fire_pthread(), fireable::graph, fireable::iloop, MAX_ATTEMPTS, graph::mem_option, THREAD_ATTEMPT_SLEEP, topologic_debug, fireable::vertex, vertex_result::vertex_argv, vertex_result::vertex_size, and WAIT.
Referenced by fire().
Author
Generated automatically by Doxygen for Topologic from the source code.