src/topologic_json.c
NAME
src/topologic_json.c
SYNOPSIS
#include '../include/topologic.h'
Functions
void print_edges (struct graph *graph, struct AVLTree *edges, const char *indent, FILE *out)
void print_state (struct graph *graph, FILE *out)
void print_graph (struct graph *graph)
Function Documentation
void print_edges (struct graph * graph, struct AVLTree * edges, const char * indent, FILE * out)
References edge::a, edge::b, edge::bi_edge, destroy_stack(), edge::edge_type, edge::f, FUNCTIONS, edge::glbl, GLOBALS, edge::id, init_stack(), stack::length, graph::lvl_verbose, pop(), preorder(), and topologic_debug.
Referenced by print_state().
void print_graph (struct graph * graph)
@PARAM graph: the graph Prints the graph with desired output TODO: Print enums
References graph::context, graph::lock, graph::lvl_verbose, graph::max_loop, graph::max_state_changes, NO_VERB, graph::num_vertices, print_state(), SINGLE, AVLTree::size, graph::snapshot_timestamp, START_STOP, graph::state_count, topologic_debug, and graph::vertices.
Referenced by main(), run(), and run_single().
void print_state (struct graph * graph, FILE * out)
References destroy_stack(), vertex::edge_tree, EDGES, vertex::f, FUNCTIONS, edge::glbl, vertex::glbl, GLOBALS, vertex::id, init_stack(), inorder(), vertex::is_active, stack::length, graph::lvl_verbose, pop(), print_edges(), vertex::shared, AVLTree::size, topologic_debug, VERTICES, and graph::vertices.
Referenced by print_graph().
Author
Generated automatically by Doxygen for Topologic from the source code.