src/topologic.c
NAME
src/topologic.c
SYNOPSIS
#include '../include/topologic.h'
Functions
void sleep_ms (int milliseconds)
int start_set (struct graph *graph, int id[], int num_vertices)
int run_single (struct graph *graph, struct vertex_result **init_vertex_args)
int run (struct graph *graph, struct vertex_result **init_vertex_args)
int fire (struct graph *graph, struct vertex *vertex, struct vertex_result *args, enum STATES color, int iloop)
void * fire_pthread (void *vargp)
int switch_vertex (struct graph *graph, struct vertex *vertex, struct vertex_result *args, enum STATES color, int iloop)
int pause_graph (struct graph *graph)
int resume_graph (struct graph *graph)
Function Documentation
int fire (struct graph * graph, struct vertex * vertex, struct vertex_result * args, enum STATES color, int iloop)
@PARAM graph: the graph @PARAM vertex: A vertex to be ran @PARAM args: arguments @PARAM color: the state in which unlocks fire process if STATE is set to PRINT then fire will fail @PARAM iloop: the number of times that vertex fired in succession @RETURNS the result of the vertex fire will wake up the vertex and pass args to the vertex to compute its function and then call switch and clean itself up
References edge::a_vars, fireable::args, edge::b, edge::b_vars, BI_EDGE, edge::bi_edge_lock, BLACK, graph::black_fire, graph::black_locked, graph::black_vertex_count, fireable::color, graph::context, destroy_stack(), vertex_result::edge_argv, vertex::edge_tree, edge::edge_type, vertex::f, edge::f, fire(), edge::glbl, vertex::glbl, fireable::iloop, init_stack(), vertex::is_active, graph::lock, vertex::lock, graph::max_loop, graph::max_state_changes, NONE, graph::num_vertices, pop(), preorder(), PTHREAD_SLEEP_TIME, RED, graph::red_fire, graph::red_locked, graph::red_vertex_count, vertex::shared, sleep_ms(), graph::state, graph::state_count, SWITCH, SWITCH_UNSAFE, switch_vertex(), TERMINATE, topologic_debug, vertex_result::vertex_argv, and shared_edge::vertex_data.
Referenced by fire(), and fire_pthread().
void* fire_pthread (void * vargp)
Wrapper function for fire, fire_1 @PARAM vargp: arguments
References fireable::args, fireable::color, fire(), fireable::graph, fireable::iloop, PTHREAD_SLEEP_TIME, sleep_ms(), topologic_debug, and fireable::vertex.
Referenced by run(), and switch_vertex().
int pause_graph (struct graph * graph)
@PARAM graph: the graph @RETURN 0 for success -1 if it fails Pauses run
References graph::lock, graph::pause, graph::pause_cond, and topologic_debug.
int resume_graph (struct graph * graph)
@PARAM graph: the graph @RETURN 0 for success -1 if it fails Resumes run
References graph::lock, graph::pause, and topologic_debug.
int run (struct graph * graph, struct vertex_result ** vertex_args)
@PARAM graph: the graph @PARAM vertex_args: array of vertex arguments for f @RETURN 0 if run terminates normally -1 if it fails Attempts to run the graph else aborts.
References ABORT, fireable::args, BLACK, graph::black_fire, graph::black_locked, graph::black_vertex_count, fireable::color, graph::color_lock, graph::context, CONTINUE, fire_pthread(), fireable::graph, fireable::iloop, vertex::is_active, graph::lock, MAX_ATTEMPTS, graph::max_state_changes, graph::mem_option, graph::num_vertices, graph::pause, graph::pause_cond, pop(), graph::previous_color, PRINT, graph::print_flag, print_graph(), process_requests(), RED, graph::red_fire, graph::red_locked, graph::red_vertex_count, run_single(), SINGLE, graph::start, graph::state, graph::state_count, TERMINATE, THREAD_ATTEMPT_SLEEP, topologic_debug, fireable::vertex, and WAIT.
Referenced by runTest(), test_run_none(), test_run_single(), and test_run_switch().
int run_single (struct graph * graph, struct vertex_result ** init_vertex_args)
References edge::a_vars, edge::b, edge::b_vars, graph::context, destroy_stack(), vertex_result::edge_argv, vertex::edge_tree, vertex::f, edge::f, edge::glbl, vertex::glbl, init_stack(), vertex::is_active, stack::length, graph::lock, graph::max_loop, graph::max_state_changes, graph::num_vertices, graph::pause, graph::pause_cond, pop(), preorder(), print_graph(), process_requests(), vertex::shared, SINGLE, graph::start, graph::state, graph::state_count, TERMINATE, topologic_debug, vertex_result::vertex_argv, and shared_edge::vertex_data.
Referenced by run().
void sleep_ms (int milliseconds)
Referenced by fire(), and fire_pthread().
int start_set (struct graph * graph, int id[], int num_vertices)
@PARAM graph: the graph, @PARAM id: the ids of the vertices @PARAM num_vertices: number of vertices @RETURN -1 for fail if any vertex fails; 0 for success Creates multiple contexts that are ran in parallel Handle errors
Given vertx failed, so at this point, free the vertices and leave
References graph::context, find(), vertex::id, pop(), push(), SINGLE, graph::start, topologic_debug, and graph::vertices.
Referenced by runTest(), setup_start_set(), and setupSelfEdge().
int switch_vertex (struct graph * graph, struct vertex * vertex, struct vertex_result * args, enum STATES color, int iloop)
@PARAM graph: the graph @PARAM vertex: The vertex in which just fire @PARAM args; The result of the vertex Upon call the switch function will compute the edge functions connected to the vertex @PARAM iloop: the number of times that vertex fired in succession @RETURNS 0 On success; the vertex connected to the successful edge will be fired; -1 on failure
References ABORT, fireable::args, fireable::color, CONTINUE, vertex_result::edge_argv, vertex_result::edge_size, fire_pthread(), fireable::graph, fireable::iloop, MAX_ATTEMPTS, graph::mem_option, THREAD_ATTEMPT_SLEEP, topologic_debug, fireable::vertex, vertex_result::vertex_argv, vertex_result::vertex_size, and WAIT.
Referenced by fire().
Author
Generated automatically by Doxygen for Topologic from the source code.