.TH "include/topylogic.h" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/topylogic.h
.SH SYNOPSIS
.br
.PP
\fC#include <Python\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtopylogic_function\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "PyObject * \fBcallback\fP (struct \fBtopylogic_function\fP *tf, PyObject *args)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "PyObject* callback (struct \fBtopylogic_function\fP * tf, PyObject * args)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
