.TH "topylogic_function" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
topylogic_function
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <topylogic\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "PyObject * \fBf\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "PyObject* topylogic_function::f"


.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
