src/vertex.c
NAME
src/vertex.c
SYNOPSIS
#include '../include/topologic.h'
Functions
struct vertex * create_vertex (struct graph *graph, void(*f)(struct graph *, struct vertex_result *, void *, void *), int id, void *glbl)
int remove_vertex (struct graph *graph, struct vertex *vertex)
int remove_vertex_id (struct graph *graph, int id)
int modify_vertex (struct vertex *vertex, void(*f)(struct graph *, struct vertex_result *, void *, void *), void *glbl)
int modify_shared_edge_vars (struct vertex *vertex, void *edge_vars)
Function Documentation
struct vertex* create_vertex (struct graph * graph, void(*)(struct graph *, struct vertex_result *, void *, void *) f, int id, void * glbl)
@PARAM graph: the graph @PARAM f: a function @PARAM id: vertex id to be used: MUST BE UNIQUE @PARAM glbl: global variables @RETURN vertex: a vertex to be used in a graph On creation a process will be spawned for the vertex The vertex will compute function f when called NOTE: NULL glbl will mean no global variables. f cannot be NULL.
References graph::context, vertex::context, destroy_avl(), vertex::edge_tree, vertex::f, vertex::glbl, vertex::id, init_avl(), insert(), vertex::is_active, vertex::joining_vertices, graph::lock, vertex::lock, vertex::shared, SINGLE, topologic_debug, shared_edge::vertex_data, and graph::vertices.
Referenced by procces_request(), and test_graph_insert_vertex().
int modify_shared_edge_vars (struct vertex * vertex, void * edge_vars)
@PARAM vertex: a vertex @PARAM edge_vars: shared variables @RETURN 0 for success; -1 for fail Modifies the vertices shared variables with it's edges
References vertex::context, vertex::lock, vertex::shared, SINGLE, topologic_debug, and shared_edge::vertex_data.
Referenced by procces_request().
int modify_vertex (struct vertex * vertex, void(*)(struct graph *, struct vertex_result *, void *, void *) f, void * glbl)
@PARAM vertex: a vertex @PARAM f: a function @PARAM glbl: global variables NOTE: NULL f, or glbl will mean no change. @RETURN 0 for success; -1 for fail Modifies the vertices function
References vertex::context, vertex::f, vertex::glbl, vertex::lock, SINGLE, and topologic_debug.
Referenced by procces_request(), and test_graph_modify_vertex().
int remove_vertex (struct graph * graph, struct vertex * vertex)
@PARAM graph: the graph @PARAM vertex: a vertex @RETURN 0 for sucess; -1 for fail Removes the vertex and all connected edges
References edge::a, edge::b, BI_EDGE, edge::bi_edge, edge::bi_edge_lock, graph::context, vertex::context, destroy_stack(), EDGE, vertex::edge_tree, edge::edge_type, edge::f, edge::glbl, vertex::glbl, edge::id, vertex::id, init_stack(), vertex::joining_vertices, graph::lock, vertex::lock, pop(), remove_edge_id(), remove_ID(), SELF_EDGE, vertex::shared, SINGLE, stackify(), topologic_debug, shared_edge::vertex_data, and graph::vertices.
Referenced by cleanup(), destroy_graph_avl(), procces_request(), remove_vertex_id(), and test_graph_remove_vertex().
int remove_vertex_id (struct graph * graph, int id)
@PARAM graph: the graph @PARAM id: the vertex id @RETURN 0 for sucess; -1 for fail Removes the vertex and all connected edges
References graph::context, find(), graph::lock, remove_vertex(), SINGLE, topologic_debug, and graph::vertices.
Referenced by procces_request().
Author
Generated automatically by Doxygen for Topologic from the source code.