.TH "vertex_request" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vertex_request
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vertex\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBgraph\fP * \fBgraph\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "void(* \fBf\fP )(struct \fBgraph\fP *, struct \fBvertex_result\fP *, void *, void *)"
.br
.ti -1c
.RI "void * \fBglbl\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void(* vertex_request::f) (struct \fBgraph\fP *, struct \fBvertex_result\fP *, void *, void *)"

.PP
Referenced by init(), procces_request(), setupSelfEdge(), setupVertex(), test_create_request(), and test_submit_request()\&.
.SS "void* vertex_request::glbl"

.PP
Referenced by init(), procces_request(), setupSelfEdge(), setupVertex(), test_create_request(), and test_submit_request()\&.
.SS "struct \fBgraph\fP* vertex_request::graph"

.PP
Referenced by init(), procces_request(), setupSelfEdge(), setupVertex(), test_create_request(), and test_submit_request()\&.
.SS "int vertex_request::id"

.PP
Referenced by init(), procces_request(), setupSelfEdge(), setupVertex(), test_create_request(), and test_submit_request()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
