.TH "include/vertex.h" 3 "Mon Mar 15 2021" "Version 1.0.6" "Topologic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/vertex.h
.SH SYNOPSIS
.br
.PP
\fC#include <signal\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include '\&./stack\&.h'\fP
.br
\fC#include '\&./AVL\&.h'\fP
.br
\fC#include '\&./context\&.h'\fP
.br
\fC#include '\&./graph\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBvertex_result\fP"
.br
.ti -1c
.RI "union \fBshared_edge\fP"
.br
.ti -1c
.RI "struct \fBvertex\fP"
.br
.ti -1c
.RI "struct \fBvertex_request\fP"
.br
.ti -1c
.RI "struct \fBmod_vertex_request\fP"
.br
.ti -1c
.RI "struct \fBmod_edge_vars_request\fP"
.br
.ti -1c
.RI "struct \fBdestroy_vertex_request\fP"
.br
.ti -1c
.RI "struct \fBdestroy_vertex_id_request\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Topologic from the source code\&.
