include/windows_wrap.h
NAME
include/windows_wrap.h
SYNOPSIS
#include <windows.h>
#include <process.h>
#include <stdbool.h>
Typedefs
typedef void pthread_mutexattr_t
typedef void pthread_condattr_t
typedef void pthread_attr_t
typedef CRITICAL_SECTION pthread_mutex_t
typedef HANDLE pthread_t
typedef CONDITION_VARIABLE pthread_cond_t
Functions
int pthread_create (pthread_t *thread, pthread_attr_t *attr, void *(*start_routine)(void *), void *arg)
int pthread_detach (pthread_t)
int pthread_exit (void *retval)
int pthread_mutex_init (pthread_mutex_t *mutex, pthread_mutexattr_t *attr)
int pthread_mutex_destroy (pthread_mutex_t *mutex)
int pthread_mutex_lock (pthread_mutex_t *mutex)
int pthread_mutex_unlock (pthread_mutex_t *mutex)
int pthread_cond_init (pthread_cond_t *cond, pthread_condattr_t *attr)
int pthread_cond_destroy (pthread_cond_t *cond)
int pthread_cond_wait (pthread_cond_t *cond, pthread_mutex_t *mutex)
int pthread_cond_signal (pthread_cond_t *cond)
Typedef Documentation
typedef void pthread_attr_t
typedef CONDITION_VARIABLE pthread_cond_t
typedef void pthread_condattr_t
typedef CRITICAL_SECTION pthread_mutex_t
typedef void pthread_mutexattr_t
SRC: https://nachtimwald.com/2019/04/05/cross-platform-thread-wrapper/
typedef HANDLE pthread_t
Function Documentation
int pthread_cond_destroy (pthread_cond_t * cond)
Referenced by destroy_graph(), and graph_init().
int pthread_cond_init (pthread_cond_t * cond, pthread_condattr_t * attr)
Referenced by graph_init().
int pthread_cond_signal (pthread_cond_t * cond)
Referenced by fire(), and pause_graph().
int pthread_cond_wait (pthread_cond_t * cond, pthread_mutex_t * mutex)
Referenced by destroy_graph(), run(), and run_single().
int pthread_create (pthread_t * thread, pthread_attr_t * attr, void *(*)(void *) start_routine, void * arg)
Referenced by run(), and switch_vertex().
int pthread_detach (pthread_t)
Referenced by run(), and switch_vertex().
int pthread_exit (void * retval)
Referenced by fire_pthread(), and run().
int pthread_mutex_destroy (pthread_mutex_t * mutex)
Referenced by destroy_graph(), graph_init(), remove_edge(), remove_edge_id(), and remove_vertex().
int pthread_mutex_init (pthread_mutex_t * mutex, pthread_mutexattr_t * attr)
Referenced by create_bi_edge(), create_vertex(), and graph_init().
int pthread_mutex_lock (pthread_mutex_t * mutex)
Referenced by create_edge(), create_vertex(), fire(), modify_edge(), modify_shared_edge_vars(), modify_vertex(), pause_graph(), print_graph(), process_requests(), remove_edge(), remove_edge_id(), remove_vertex(), remove_vertex_id(), resume_graph(), run(), run_single(), and submit_request().
int pthread_mutex_unlock (pthread_mutex_t * mutex)
Referenced by create_edge(), create_vertex(), fire(), modify_edge(), modify_shared_edge_vars(), modify_vertex(), pause_graph(), print_graph(), process_requests(), remove_edge(), remove_edge_id(), remove_vertex(), remove_vertex_id(), resume_graph(), run(), run_single(), and submit_request().
Author
Generated automatically by Doxygen for Topologic from the source code.